"""REST API router.

This module defines the REST API endpoints for the agent framework,
including session management and message handling.

参考：详细设计.md 第8节
"""
import logging
import json
from datetime import datetime, timezone
from typing import List, Optional, Dict, Any
from asyncio import Queue

from fastapi import APIRouter, HTTPException, Depends, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from ..dependencies import get_session_manager
from ...core.session_manager import SessionManager
from ...interfaces.session import SessionContext, Message

logger = logging.getLogger("agent_framework.gateway.rest")


# ============================================================================
# Pydantic Models for Request/Response
# ============================================================================

class CreateSessionRequest(BaseModel):
    """Request model for creating a new session.

    Attributes:
        user_id: ID of the user creating the session.
        session_type: Type of session ('private' or 'group').
        participants: Optional list of additional participant IDs.
    """
    user_id: str
    session_type: str = "private"
    participants: Optional[List[str]] = None


class CreateSessionResponse(BaseModel):
    """Response model for session creation.

    Attributes:
        session_id: Unique identifier for the created session.
        session_type: Type of session.
        participants: List of participant IDs.
        status: Session status.
        created_at: Session creation timestamp.
    """
    session_id: str
    session_type: str
    participants: List[str]
    status: str
    created_at: datetime


class SessionInfoResponse(BaseModel):
    """Response model for session information.

    Attributes:
        session_id: Unique identifier for the session.
        session_type: Type of session.
        participants: List of participant IDs.
        status: Session status.
        message_count: Number of messages in the session.
        created_at: Session creation timestamp.
        last_active: Last activity timestamp.
    """
    session_id: str
    session_type: str
    participants: List[str]
    status: str
    message_count: int
    created_at: datetime
    last_active: datetime


class SendMessageRequest(BaseModel):
    """Request model for sending a message.

    Attributes:
        content: Message content.
        sender_id: Optional ID of the message sender.
    """
    content: str
    sender_id: Optional[str] = None


class SendMessageResponse(BaseModel):
    """Response model for message sending.

    Attributes:
        session_id: ID of the session.
        events: List of events generated by the agent.
        message_count: Total number of messages after sending.
    """
    session_id: str
    events: List[Dict[str, Any]]
    message_count: int


class MessageHistoryResponse(BaseModel):
    """Response model for message history.

    Attributes:
        session_id: ID of the session.
        messages: List of messages in the session.
        total_count: Total number of messages.
    """
    session_id: str
    messages: List[Dict[str, Any]]
    total_count: int


class ErrorResponse(BaseModel):
    """Error response model.

    Attributes:
        error: Error type or summary.
        detail: Detailed error description.
    """
    error: str
    detail: Optional[str] = None


# ============================================================================
# Helper Functions
# ============================================================================

def _message_to_dict(message: Message) -> Dict[str, Any]:
    """Convert a Message object to a dictionary.

    Args:
        message: Message object to convert.

    Returns:
        Dictionary representation of the message.
    """
    return {
        "role": message.role,
        "content": message.content,
        "sender_id": message.sender_id,
        "timestamp": message.timestamp.isoformat() if message.timestamp else None
    }


def _session_to_response(ctx: SessionContext) -> CreateSessionResponse:
    """Convert a SessionContext to a CreateSessionResponse.

    Args:
        ctx: SessionContext to convert.

    Returns:
        CreateSessionResponse instance.
    """
    return CreateSessionResponse(
        session_id=ctx.session_id,
        session_type=ctx.session_type,
        participants=ctx.participants,
        status=ctx.status,
        created_at=ctx.created_at
    )


def _session_to_info(ctx: SessionContext) -> SessionInfoResponse:
    """Convert a SessionContext to a SessionInfoResponse.

    Args:
        ctx: SessionContext to convert.

    Returns:
        SessionInfoResponse instance.
    """
    return SessionInfoResponse(
        session_id=ctx.session_id,
        session_type=ctx.session_type,
        participants=ctx.participants,
        status=ctx.status,
        message_count=len(ctx.messages),
        created_at=ctx.created_at,
        last_active=ctx.last_active
    )


# ============================================================================
# REST API Router
# ============================================================================

router = APIRouter(prefix="/api/v1")


@router.get("/health")
async def health_check():
    """Health check endpoint.

    Returns:
        dict: Status information indicating the service is healthy.
    """
    return {"status": "ok", "service": "agent-framework"}


@router.get("/")
async def root():
    """Root endpoint.

    Returns:
        dict: Welcome message.
    """
    return {"message": "Welcome to Agent Framework API"}


@router.post("/sessions", response_model=CreateSessionResponse)
async def create_session(
    request: CreateSessionRequest,
    session_manager: Optional[SessionManager] = Depends(get_session_manager)
):
    """Create a new session.

    Args:
        request: CreateSessionRequest containing session parameters.
        session_manager: SessionManager dependency.

    Returns:
        CreateSessionResponse with session details.

    Raises:
        HTTPException: If session creation fails.
    """
    if session_manager is None:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Service unavailable", detail="SessionManager not initialized").dict()
        )

    try:
        ctx = await session_manager.create_session(
            user_id=request.user_id,
            session_type=request.session_type,
            participants=request.participants
        )
        return _session_to_response(ctx)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Session creation failed", detail=str(e)).dict()
        )


@router.get("/sessions/{session_id}", response_model=SessionInfoResponse)
async def get_session(
    session_id: str,
    session_manager: Optional[SessionManager] = Depends(get_session_manager)
):
    """Get session information.

    Args:
        session_id: ID of the session to retrieve.
        session_manager: SessionManager dependency.

    Returns:
        SessionInfoResponse with session details.

    Raises:
        HTTPException: If session is not found or retrieval fails.
    """
    if session_manager is None:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Service unavailable", detail="SessionManager not initialized").dict()
        )

    try:
        ctx = await session_manager.get_session(session_id)
        if ctx is None:
            raise HTTPException(
                status_code=404,
                detail=ErrorResponse(
                    error="Session not found",
                    detail=f"Session with ID '{session_id}' does not exist"
                ).dict()
            )
        return _session_to_info(ctx)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Failed to retrieve session", detail=str(e)).dict()
        )


@router.post("/sessions/{session_id}/messages")
async def send_message(
    session_id: str,
    request: SendMessageRequest,
    session_manager: Optional[SessionManager] = Depends(get_session_manager)
):
    """Send a message to a session and receive streaming SSE response.

    Args:
        session_id: ID of the session to send message to.
        request: SendMessageRequest containing message content.
        session_manager: SessionManager dependency.

    Returns:
        StreamingResponse with text/event-stream content type.
    """
    if session_manager is None:
        raise HTTPException(
            status_code=500,
            detail="SessionManager not initialized"
        )

    async def event_generator():
        try:
            user_msg = {
                "role": "user",
                "content": request.content,
                "sender_id": request.sender_id
            }

            async for event in session_manager.process_message_stream(session_id, user_msg):
                event_data = {
                    "type": event.type,
                    "content": event.content,
                    "metadata": event.metadata,
                    "timestamp": event.timestamp.isoformat() if event.timestamp else None
                }
                yield f"data: {json.dumps(event_data)}\n\n"

            yield f"data: {{\"type\": \"done\", \"content\": \"\"}}\n\n"

        except ValueError as e:
            error_data = {"type": "error", "content": str(e)}
            yield f"data: {json.dumps(error_data)}\n\n"
        except Exception as e:
            logger.error(f"Error in stream processing session {session_id}: {e}", exc_info=True)
            error_data = {"type": "error", "content": f"Processing error: {str(e)}"}
            yield f"data: {json.dumps(error_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


@router.post("/sessions/{session_id}/messages/stream")
async def send_message_stream(
    session_id: str,
    request: SendMessageRequest,
    session_manager: Optional[SessionManager] = Depends(get_session_manager)
):
    """Send a message to a session and receive streaming SSE response.

    Args:
        session_id: ID of the session to send message to.
        request: SendMessageRequest containing message content.
        session_manager: SessionManager dependency.

    Returns:
        StreamingResponse with text/event-stream content type.
    """
    if session_manager is None:
        raise HTTPException(
            status_code=500,
            detail="SessionManager not initialized"
        )

    async def event_generator():
        try:
            # Prepare message dict
            user_msg = {
                "role": "user",
                "content": request.content,
                "sender_id": request.sender_id
            }

            # Stream events as they are generated
            async for event in session_manager.process_message_stream(session_id, user_msg):
                event_data = {
                    "type": event.type,
                    "content": event.content,
                    "metadata": event.metadata,
                    "timestamp": event.timestamp.isoformat() if event.timestamp else None
                }
                yield f"data: {json.dumps(event_data)}\n\n"

            # Send final done signal
            yield f"data: {{\"type\": \"done\", \"content\": \"\"}}\n\n"

        except ValueError as e:
            error_data = {"type": "error", "content": str(e)}
            yield f"data: {json.dumps(error_data)}\n\n"
        except Exception as e:
            logger.error(f"Error in stream processing session {session_id}: {e}", exc_info=True)
            error_data = {"type": "error", "content": f"Processing error: {str(e)}"}
            yield f"data: {json.dumps(error_data)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


@router.get("/sessions/{session_id}/messages", response_model=MessageHistoryResponse)
async def get_message_history(
    session_id: str,
    limit: Optional[int] = Query(None, ge=1, le=100, description="Maximum number of messages to return"),
    session_manager: Optional[SessionManager] = Depends(get_session_manager)
):
    """Get message history for a session.

    Args:
        session_id: ID of the session to get messages from.
        limit: Optional maximum number of messages to return (1-100).
        session_manager: SessionManager dependency.

    Returns:
        MessageHistoryResponse with message list.

    Raises:
        HTTPException: If session is not found or retrieval fails.
    """
    if session_manager is None:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Service unavailable", detail="SessionManager not initialized").dict()
        )

    try:
        ctx = await session_manager.get_session(session_id)
        if ctx is None:
            raise HTTPException(
                status_code=404,
                detail=ErrorResponse(
                    error="Session not found",
                    detail=f"Session with ID '{session_id}' does not exist"
                ).dict()
            )

        # Get messages, optionally limited
        messages = ctx.messages
        if limit is not None:
            messages = messages[-limit:]  # Return most recent messages

        # Convert messages to dict format
        message_dicts = [_message_to_dict(msg) for msg in messages]

        return MessageHistoryResponse(
            session_id=session_id,
            messages=message_dicts,
            total_count=len(ctx.messages)
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(error="Failed to retrieve messages", detail=str(e)).dict()
        )